---
collections:
  - name: community.general
  - name: ansible.posix
collections:
  - name: community.kubernetes
    version: ">=2.0.1"
collections:
  - name: community.kubernetes
    version: ">=2.0.0"
